version: "3.9"

services:
    postgres:
        image: postgres:latest
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data

    storedge-core:
        container_name: storedge-core
        image: ghcr.io/suiramdev/storedge-core:main
        env_file: .env
        depends_on:
            - postgres
        ports:
            - "4000:4000"

volumes:
    pg_data:
