version: "3.9"
services:
    postgres:
        image: postgres:latest
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data

    postgres-init:
        build:
            context: .
        command: npx prisma db push
        env_file: .env
        depends_on:
            - postgres

    postgres-seeding:
        build:
            context: .
        command: npx prisma db seed
        env_file: .env
        depends_on:
            - postgres-init

    storedge-core:
        build:
            context: .
        env_file: .env
        depends_on:
            - postgres-seeding
        ports:
            - "4000:4000"

volumes:
    pg_data:
